name: AppName
options:
  bundleIdPrefix: io.agsoares
targets:
  AppName:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    sources: 
      - path: Sources
        excludes: ['**/.gitkeep']
    scheme:
      testTargets:
        - AppNameTests
    preBuildScripts:
      - path: Scripts/swiftgen.sh
        name: Swiftgen
    postCompileScripts:
      - path: Scripts/swiftlint.sh
        name: Swiftlint
  AppNameTests:
    type: bundle.unit-test
    platform: iOS 
    sources: Tests
    dependencies:
      - target: AppName


