name: Test
on: 
  push:
    branches:
      - master
  pull_request
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Mint
        id: cache-mint
        uses: actions/cache@v1
        with:
          path: /usr/local/lib/mint
          key: ${{ runner.os }}-cache-mint-${{ hashFiles('**/Mintfile') }}

      - name: Cache Pods
        id: cache-pods
        uses: actions/cache@v1
        with:
          path: Pods
          key: ${{ runner.os }}-cache-pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Bootstrap
        run: make bootstrap

      - name: Build and Test
        run: |
          xcodebuild clean test -workspace AppName.xcworkspace -scheme AppName -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty && exit ${PIPESTATUS[0]}
        env: 
          destination: ${{ matrix.destination }}